# Generated by Django 3.0.8 on 2020-07-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20200715_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email is already registered.'}, max_length=254, unique=True),
        ),
    ]
